2014-01-04 00:11:50+0100 [-] Received SIGINT, shutting down.
2014-01-04 00:11:50+0100 [__main__.CubeWorldServer] (TCP Port 12345 Closed)
2014-01-04 00:11:50+0100 [__main__.CubeWorldServer] Stopping factory <__main__.CubeWorldServer instance at 0x2732638>
2014-01-04 00:11:50+0100 [MasterClient (UDP)] (UDP Port 12345 Closed)
2014-01-04 00:11:50+0100 [MasterClient (UDP)] Stopping protocol <scripts.master.MasterClient instance at 0x2732710>
2014-01-04 00:11:50+0100 [-] Main loop terminated.
2014-01-04 00:11:50+0100 [-] Database connection closed.
2014-01-04 00:11:52+0100 [-] cuwo server started on Sat Jan  4 00:11:52 2014
2014-01-04 00:11:52+0100 [-] Log opened.
2014-01-04 00:11:52+0100 [-] [INFO] Loaded script 'log'
2014-01-04 00:11:52+0100 [-] [INFO] Loaded script 'ddos'
2014-01-04 00:11:52+0100 [-] [INFO] Loaded script 'commands'
2014-01-04 00:11:52+0100 [-] [INFO] Loaded script 'welcome'
2014-01-04 00:11:52+0100 [-] [INFO] Loaded script 'ban'
2014-01-04 00:11:52+0100 [-] [INFO] Loaded script 'console'
2014-01-04 00:11:52+0100 [-] [INFO] Loaded script 'anticheat'
2014-01-04 00:11:52+0100 [-] CubeWorldServer starting on 12345
2014-01-04 00:11:52+0100 [-] Starting factory <__main__.CubeWorldServer instance at 0x2117dd0>
2014-01-04 00:11:52+0100 [-] [INFO] Server is listening on port 12345
2014-01-04 00:11:52+0100 [-] MasterClient starting on 12345
2014-01-04 00:11:52+0100 [-] Starting protocol <scripts.master.MasterClient instance at 0x2117ea8>
2014-01-04 00:12:02+0100 [-] Unhandled error in Deferred:
2014-01-04 00:12:02+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1169, in run
	    self.mainLoop()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1178, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 800, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 215, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 134, in maybeDeferred
	    result = f(*args, **kw)
	  File "scripts/master.py", line 105, in update
	    self.send_packet(data.get(), self.address)
	  File "scripts/master.py", line 50, in send_packet
	    self.transport.write(data, addr)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 184, in write
	    return self.socket.sendto(datagram, addr)
	socket.error: [Errno 1] Operation not permitted
	
2014-01-04 00:12:02+0100 [__main__.CubeWorldServer] [DATABASE] Connected to database using SQLite 3.7.13
2014-01-04 00:12:02+0100 [CubeWorldConnection,0,93.200.65.91] >>> Player Jakky89 Ranger L1 Sniper #1 [93.200.65.91] joined the game
2014-01-04 00:12:02+0100 [CubeWorldConnection,0,93.200.65.91] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 586, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 199, in doRead
	    rval = self.protocol.dataReceived(data)
	  File "/home/cubeworld/server/cuwo/server.py", line 139, in dataReceived
	    self.packet_handler.feed(data)
	  File "cuwo/packet.py", line 721, in feed
	    self.callback(packet)
	  File "/home/cubeworld/server/cuwo/server.py", line 176, in on_packet
	    handler(packet)
	  File "/home/cubeworld/server/cuwo/server.py", line 204, in on_entity_packet
	    self.on_pos_update()
	  File "/home/cubeworld/server/cuwo/server.py", line 234, in on_pos_update
	    if chunk != self.current_chunk:
	exceptions.AttributeError: CubeWorldConnection instance has no attribute 'current_chunk'
	
2014-01-04 00:12:02+0100 [CubeWorldConnection,0,93.200.65.91] [INFO] Player Jakky89 #1 left the game.
2014-01-04 00:14:37+0100 [-] Received SIGINT, shutting down.
2014-01-04 00:14:37+0100 [__main__.CubeWorldServer] (TCP Port 12345 Closed)
2014-01-04 00:14:37+0100 [__main__.CubeWorldServer] Stopping factory <__main__.CubeWorldServer instance at 0x2117dd0>
2014-01-04 00:14:37+0100 [MasterClient (UDP)] (UDP Port 12345 Closed)
2014-01-04 00:14:37+0100 [MasterClient (UDP)] Stopping protocol <scripts.master.MasterClient instance at 0x2117ea8>
2014-01-04 00:14:37+0100 [-] Main loop terminated.
2014-01-04 00:14:37+0100 [-] Database connection closed.
2014-01-04 00:14:38+0100 [-] cuwo server started on Sat Jan  4 00:14:38 2014
2014-01-04 00:14:38+0100 [-] Log opened.
2014-01-04 00:14:38+0100 [-] [INFO] Loaded script 'log'
2014-01-04 00:14:38+0100 [-] [INFO] Loaded script 'ddos'
2014-01-04 00:14:38+0100 [-] [INFO] Loaded script 'commands'
2014-01-04 00:14:38+0100 [-] [INFO] Loaded script 'welcome'
2014-01-04 00:14:38+0100 [-] [INFO] Loaded script 'ban'
2014-01-04 00:14:38+0100 [-] [INFO] Loaded script 'console'
2014-01-04 00:14:38+0100 [-] [INFO] Loaded script 'anticheat'
2014-01-04 00:14:38+0100 [-] CubeWorldServer starting on 12345
2014-01-04 00:14:38+0100 [-] Starting factory <__main__.CubeWorldServer instance at 0x16d45a8>
2014-01-04 00:14:38+0100 [-] [INFO] Server is listening on port 12345
2014-01-04 00:14:38+0100 [-] MasterClient starting on 12345
2014-01-04 00:14:38+0100 [-] Starting protocol <scripts.master.MasterClient instance at 0x16d4680>
2014-01-04 00:14:48+0100 [-] Unhandled error in Deferred:
2014-01-04 00:14:48+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1169, in run
	    self.mainLoop()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1178, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 800, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 215, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 134, in maybeDeferred
	    result = f(*args, **kw)
	  File "scripts/master.py", line 105, in update
	    self.send_packet(data.get(), self.address)
	  File "scripts/master.py", line 50, in send_packet
	    self.transport.write(data, addr)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 184, in write
	    return self.socket.sendto(datagram, addr)
	socket.error: [Errno 1] Operation not permitted
	
2014-01-04 00:14:49+0100 [__main__.CubeWorldServer] [DATABASE] Connected to database using SQLite 3.7.13
2014-01-04 00:14:49+0100 [CubeWorldConnection,0,93.200.65.91] >>> Player Jakky89 Ranger L1 Sniper #1 [93.200.65.91] joined the game
2014-01-04 00:15:18+0100 [CubeWorldConnection,0,93.200.65.91] [COMMAND] Jakky89: /whois Jakky89
2014-01-04 00:15:28+0100 [CubeWorldConnection,0,93.200.65.91] [CHAT] Jakky89: w
2014-01-04 00:16:11+0100 [CubeWorldConnection,0,93.200.65.91] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 586, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 199, in doRead
	    rval = self.protocol.dataReceived(data)
	  File "/home/cubeworld/server/cuwo/server.py", line 138, in dataReceived
	    self.packet_handler.feed(data)
	  File "cuwo/packet.py", line 721, in feed
	    self.callback(packet)
	  File "/home/cubeworld/server/cuwo/server.py", line 175, in on_packet
	    handler(packet)
	  File "/home/cubeworld/server/cuwo/server.py", line 262, in on_interact_packet
	    item = self.server.remove_item(packet.chunk_x, packet.chunk_y, packet.item_index)
	  File "/home/cubeworld/server/cuwo/server.py", line 694, in remove_item
	    chunk = self.server.world.get_chunk_unscaled(chunk_x, chunk_y)
	exceptions.AttributeError: CubeWorldServer instance has no attribute 'server'
	
2014-01-04 00:16:11+0100 [CubeWorldConnection,0,93.200.65.91] [INFO] Player Jakky89 #1 left the game.
2014-01-04 00:16:46+0100 [-] Received SIGINT, shutting down.
2014-01-04 00:16:46+0100 [__main__.CubeWorldServer] (TCP Port 12345 Closed)
2014-01-04 00:16:46+0100 [__main__.CubeWorldServer] Stopping factory <__main__.CubeWorldServer instance at 0x16d45a8>
2014-01-04 00:16:46+0100 [MasterClient (UDP)] (UDP Port 12345 Closed)
2014-01-04 00:16:46+0100 [MasterClient (UDP)] Stopping protocol <scripts.master.MasterClient instance at 0x16d4680>
2014-01-04 00:16:46+0100 [-] Main loop terminated.
2014-01-04 00:16:46+0100 [-] Database connection closed.
2014-01-04 00:20:08+0100 [-] cuwo server started on Sat Jan  4 00:20:08 2014
2014-01-04 00:20:08+0100 [-] Log opened.
2014-01-04 00:20:08+0100 [-] [INFO] Loaded script 'log'
2014-01-04 00:20:08+0100 [-] [INFO] Loaded script 'ddos'
2014-01-04 00:20:08+0100 [-] [INFO] Loaded script 'commands'
2014-01-04 00:20:08+0100 [-] [INFO] Loaded script 'welcome'
2014-01-04 00:20:08+0100 [-] [INFO] Loaded script 'ban'
2014-01-04 00:20:08+0100 [-] [INFO] Loaded script 'console'
2014-01-04 00:20:08+0100 [-] [INFO] Loaded script 'anticheat'
2014-01-04 00:20:08+0100 [-] CubeWorldServer starting on 12345
2014-01-04 00:20:08+0100 [-] Starting factory <__main__.CubeWorldServer instance at 0x1c9b5a8>
2014-01-04 00:20:08+0100 [-] [INFO] Server is listening on port 12345
2014-01-04 00:20:08+0100 [-] MasterClient starting on 12345
2014-01-04 00:20:08+0100 [-] Starting protocol <scripts.master.MasterClient instance at 0x1c9b680>
2014-01-04 00:20:18+0100 [-] Unhandled error in Deferred:
2014-01-04 00:20:18+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1169, in run
	    self.mainLoop()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1178, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 800, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 215, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 134, in maybeDeferred
	    result = f(*args, **kw)
	  File "scripts/master.py", line 105, in update
	    self.send_packet(data.get(), self.address)
	  File "scripts/master.py", line 50, in send_packet
	    self.transport.write(data, addr)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 184, in write
	    return self.socket.sendto(datagram, addr)
	socket.error: [Errno 1] Operation not permitted
	
2014-01-04 00:20:32+0100 [__main__.CubeWorldServer] [DATABASE] Connected to database using SQLite 3.7.13
2014-01-04 00:20:32+0100 [CubeWorldConnection,0,93.200.65.91] >>> Player Jakky89 Ranger L1 Sniper #1 [93.200.65.91] joined the game
2014-01-04 00:20:59+0100 [CubeWorldConnection,0,93.200.65.91] [CHAT] Jakky89: wwwa
2014-01-04 00:21:35+0100 [CubeWorldConnection,0,93.200.65.91] [CHAT] Jakky89: w
2014-01-04 00:22:48+0100 [CubeWorldConnection,0,93.200.65.91] Traceback (most recent call last):
2014-01-04 00:22:48+0100 [CubeWorldConnection,0,93.200.65.91]   File "cuwo/script.py", line 224, in call_command
2014-01-04 00:22:48+0100 [CubeWorldConnection,0,93.200.65.91]     ret = f(user, *args) or ''
2014-01-04 00:22:48+0100 [CubeWorldConnection,0,93.200.65.91]   File "scripts/commands.py", line 254, in list
2014-01-04 00:22:48+0100 [CubeWorldConnection,0,93.200.65.91]     return '[INFO] %s/%s players online: %s' % (plcount, config.max_players, ', '.join(plrs))
2014-01-04 00:22:48+0100 [CubeWorldConnection,0,93.200.65.91] NameError: global name 'config' is not defined
2014-01-04 00:22:48+0100 [CubeWorldConnection,0,93.200.65.91] [COMMAND] Jakky89: /list
2014-01-04 00:22:52+0100 [CubeWorldConnection,0,93.200.65.91] [COMMAND] Jakky89: /online
2014-01-04 00:22:53+0100 [CubeWorldConnection,0,93.200.65.91] [COMMAND] Jakky89: /tell
2014-01-04 00:22:58+0100 [CubeWorldConnection,0,93.200.65.91] [COMMAND] Jakky89: /tell Jakky89 test
2014-01-04 00:23:06+0100 [CubeWorldConnection,0,93.200.65.91] [COMMAND] Jakky89: /whois jakky89
2014-01-04 00:23:10+0100 [CubeWorldConnection,0,93.200.65.91] [COMMAND] Jakky89: /say
2014-01-04 00:23:47+0100 [CubeWorldConnection,0,93.200.65.91] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 586, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 199, in doRead
	    rval = self.protocol.dataReceived(data)
	  File "/home/cubeworld/server/cuwo/server.py", line 138, in dataReceived
	    self.packet_handler.feed(data)
	  File "cuwo/packet.py", line 721, in feed
	    self.callback(packet)
	  File "/home/cubeworld/server/cuwo/server.py", line 175, in on_packet
	    handler(packet)
	  File "/home/cubeworld/server/cuwo/server.py", line 259, in on_interact_packet
	    self.server.drop_item(packet.item_data, pos)
	  File "/home/cubeworld/server/cuwo/server.py", line 701, in drop_item
	    if len(chunk.item_list) > constants.MAX_ITEMS_PER_CHUNK:
	exceptions.AttributeError: 'module' object has no attribute 'MAX_ITEMS_PER_CHUNK'
	
2014-01-04 00:23:47+0100 [CubeWorldConnection,0,93.200.65.91] [INFO] Player Jakky89 #1 left the game.
2014-01-04 00:24:04+0100 [-] Received SIGINT, shutting down.
2014-01-04 00:24:04+0100 [__main__.CubeWorldServer] (TCP Port 12345 Closed)
2014-01-04 00:24:04+0100 [__main__.CubeWorldServer] Stopping factory <__main__.CubeWorldServer instance at 0x1c9b5a8>
2014-01-04 00:24:04+0100 [MasterClient (UDP)] (UDP Port 12345 Closed)
2014-01-04 00:24:04+0100 [MasterClient (UDP)] Stopping protocol <scripts.master.MasterClient instance at 0x1c9b680>
2014-01-04 00:24:04+0100 [-] Main loop terminated.
2014-01-04 00:24:04+0100 [-] Database connection closed.
2014-01-04 00:25:36+0100 [-] cuwo server started on Sat Jan  4 00:25:36 2014
2014-01-04 00:25:36+0100 [-] Log opened.
2014-01-04 00:25:36+0100 [-] [INFO] Loaded script 'log'
2014-01-04 00:25:36+0100 [-] [INFO] Loaded script 'ddos'
2014-01-04 00:25:36+0100 [-] [INFO] Loaded script 'commands'
2014-01-04 00:25:36+0100 [-] [INFO] Loaded script 'welcome'
2014-01-04 00:25:36+0100 [-] [INFO] Loaded script 'ban'
2014-01-04 00:25:36+0100 [-] [INFO] Loaded script 'console'
2014-01-04 00:25:36+0100 [-] [INFO] Loaded script 'anticheat'
2014-01-04 00:25:36+0100 [-] CubeWorldServer starting on 12345
2014-01-04 00:25:36+0100 [-] Starting factory <__main__.CubeWorldServer instance at 0x262dbd8>
2014-01-04 00:25:36+0100 [-] [INFO] Server is listening on port 12345
2014-01-04 00:25:36+0100 [-] MasterClient starting on 12345
2014-01-04 00:25:36+0100 [-] Starting protocol <scripts.master.MasterClient instance at 0x262dc20>
2014-01-04 00:25:46+0100 [-] Unhandled error in Deferred:
2014-01-04 00:25:46+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1169, in run
	    self.mainLoop()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1178, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 800, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 215, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 134, in maybeDeferred
	    result = f(*args, **kw)
	  File "scripts/master.py", line 105, in update
	    self.send_packet(data.get(), self.address)
	  File "scripts/master.py", line 50, in send_packet
	    self.transport.write(data, addr)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 184, in write
	    return self.socket.sendto(datagram, addr)
	socket.error: [Errno 1] Operation not permitted
	
2014-01-04 00:25:47+0100 [__main__.CubeWorldServer] [DATABASE] Connected to database using SQLite 3.7.13
2014-01-04 00:25:47+0100 [CubeWorldConnection,0,93.200.65.91] >>> Player Jakky89 Ranger L1 Sniper #1 [93.200.65.91] joined the game
2014-01-04 00:26:10+0100 [-] Unhandled error in Deferred:
2014-01-04 00:26:10+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1169, in run
	    self.mainLoop()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1178, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 800, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 215, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 134, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/cubeworld/server/cuwo/server.py", line 761, in update
	    item_list.items = chunk.item_list.copy()
	exceptions.AttributeError: 'list' object has no attribute 'copy'
	
2014-01-04 00:26:23+0100 [-] Received SIGINT, shutting down.
2014-01-04 00:26:23+0100 [__main__.CubeWorldServer] (TCP Port 12345 Closed)
2014-01-04 00:26:23+0100 [__main__.CubeWorldServer] Stopping factory <__main__.CubeWorldServer instance at 0x262dbd8>
2014-01-04 00:26:23+0100 [MasterClient (UDP)] (UDP Port 12345 Closed)
2014-01-04 00:26:23+0100 [MasterClient (UDP)] Stopping protocol <scripts.master.MasterClient instance at 0x262dc20>
2014-01-04 00:26:23+0100 [CubeWorldConnection,0,93.200.65.91] [INFO] Player Jakky89 #1 left the game.
2014-01-04 00:26:23+0100 [-] Main loop terminated.
2014-01-04 00:26:23+0100 [-] Database connection closed.
2014-01-04 00:29:55+0100 [-] cuwo server started on Sat Jan  4 00:29:55 2014
2014-01-04 00:29:55+0100 [-] Log opened.
2014-01-04 00:29:55+0100 [-] [INFO] Loaded script 'log'
2014-01-04 00:29:55+0100 [-] [INFO] Loaded script 'ddos'
2014-01-04 00:29:55+0100 [-] [INFO] Loaded script 'commands'
2014-01-04 00:29:55+0100 [-] [INFO] Loaded script 'welcome'
2014-01-04 00:29:55+0100 [-] [INFO] Loaded script 'ban'
2014-01-04 00:29:55+0100 [-] [INFO] Loaded script 'console'
2014-01-04 00:29:55+0100 [-] [INFO] Loaded script 'anticheat'
2014-01-04 00:29:55+0100 [-] CubeWorldServer starting on 12345
2014-01-04 00:29:55+0100 [-] Starting factory <__main__.CubeWorldServer instance at 0x224d638>
2014-01-04 00:29:55+0100 [-] [INFO] Server is listening on port 12345
2014-01-04 00:29:56+0100 [-] MasterClient starting on 12345
2014-01-04 00:29:56+0100 [-] Starting protocol <scripts.master.MasterClient instance at 0x224d710>
2014-01-04 00:30:06+0100 [-] Unhandled error in Deferred:
2014-01-04 00:30:06+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1169, in run
	    self.mainLoop()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1178, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 800, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 215, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 134, in maybeDeferred
	    result = f(*args, **kw)
	  File "scripts/master.py", line 105, in update
	    self.send_packet(data.get(), self.address)
	  File "scripts/master.py", line 50, in send_packet
	    self.transport.write(data, addr)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 184, in write
	    return self.socket.sendto(datagram, addr)
	socket.error: [Errno 1] Operation not permitted
	
2014-01-04 00:30:06+0100 [__main__.CubeWorldServer] [DATABASE] Connected to database using SQLite 3.7.13
2014-01-04 00:30:06+0100 [CubeWorldConnection,0,93.200.65.91] >>> Player Jakky89 Ranger L1 Sniper #1 [93.200.65.91] joined the game
2014-01-04 00:30:25+0100 [CubeWorldConnection,0,93.200.65.91] [DEBUG] Dropping item at 550292028255,550339318927
2014-01-04 00:31:01+0100 [CubeWorldConnection,0,93.200.65.91] [DEBUG] Removing item #0 from chunk 32799,32802
2014-01-04 00:31:57+0100 [CubeWorldConnection,0,93.200.65.91] [DEBUG] Dropping item at 550310049571,550336802072
2014-01-04 00:32:03+0100 [CubeWorldConnection,0,93.200.65.91] [DEBUG] Removing item #0 from chunk 32801,32802
2014-01-04 00:34:41+0100 [CubeWorldConnection,0,93.200.65.91] [DEBUG] Dropping item at 550357597297,550338828856
2014-01-04 00:34:48+0100 [CubeWorldConnection,0,93.200.65.91] [DEBUG] Removing item #0 from chunk 32803,32802
2014-01-04 00:35:35+0100 [CubeWorldConnection,0,93.200.65.91] [INFO] Player Jakky89 #1 left the game.
2014-01-04 00:41:19+0100 [-] Received SIGINT, shutting down.
2014-01-04 00:41:19+0100 [__main__.CubeWorldServer] (TCP Port 12345 Closed)
2014-01-04 00:41:19+0100 [__main__.CubeWorldServer] Stopping factory <__main__.CubeWorldServer instance at 0x224d638>
2014-01-04 00:41:19+0100 [MasterClient (UDP)] (UDP Port 12345 Closed)
2014-01-04 00:41:19+0100 [MasterClient (UDP)] Stopping protocol <scripts.master.MasterClient instance at 0x224d710>
2014-01-04 00:41:19+0100 [-] Main loop terminated.
2014-01-04 00:41:19+0100 [-] Database connection closed.
